"""A local stand-in for the EPFO UAN Card endpoint on APISetu.

This exists so the whole pipeline can be run end to end before your APISetu
credentials arrive, and so the awkward cases can be rehearsed on demand rather
than waited for.

It implements the same contract as the published spec: same path, same headers,
same request body, application/pdf on success.

Behaviour is steered by the last digit of the UAN, so a single test file can
exercise every branch:

    ...0 - 9  normal, returns a valid one page portrait PDF
    ...1      returns a LANDSCAPE pdf   (proves orientation normalising works)
    ...2      returns 404               (no record for that UAN and DOB)
    ...3      returns 503 twice then succeeds (proves retry and backoff work)
    ...4      returns HTTP 200 with an HTML error body, mislabelled as a PDF
              (proves the magic-byte check catches silent corruption)
    ...5      returns a truncated PDF    (proves the %%EOF check works)

Run it with:  python -m mockserver.server
"""

import json
import re
import zlib
from collections import defaultdict
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HOST = "127.0.0.1"
PORT = 8099
PATH = "/epfindia/v3/uncrd/certificate"

# Any non-empty value is accepted; the point is to prove the client sends them.
EXPECTED_HEADERS = ("X-APISETU-APIKEY", "X-APISETU-CLIENTID")

UAN_RE = re.compile(r"^\d{12}$")
DOB_RE = re.compile(r"^\d{2}-\d{2}-\d{4}$")

# Counts attempts per transaction so the "fail twice then succeed" case works.
_attempts: dict = defaultdict(int)


def _escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def build_pdf(uan: str, dob: str, *, landscape: bool = False) -> bytes:
    """Produce a small, genuinely valid PDF without any third-party library.

    Handwritten rather than generated so the mock has no dependencies at all and
    the file it returns is real enough for pypdf to parse and report on.
    """
    width, height = (842, 595) if landscape else (595, 842)

    lines = [
        (60, height - 90, 18, "EPFO - Universal Account Number Card"),
        (60, height - 130, 12, "(MOCK DOCUMENT - generated by the local test server)"),
        (60, height - 190, 13, f"UAN: {uan}"),
        (60, height - 220, 13, f"Date of birth: {dob}"),
        (60, height - 260, 10, "Issued via the APISetu EPFO collection, v3."),
        (60, height - 280, 10, "Not a real EPFO document and carries no legal weight."),
    ]
    parts = ["BT"]
    for x, y, size, text in lines:
        parts.append(f"/F1 {size} Tf 1 0 0 1 {x} {y} Tm ({_escape(text)}) Tj")
    parts.append("ET")
    # A border, so a landscape page is obvious at a glance when you open it.
    parts.append(f"2 w 30 30 {width - 60} {height - 60} re S")
    stream = "\n".join(parts).encode("latin-1")
    compressed = zlib.compress(stream)

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {width} {height}] "
        f"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>".encode("latin-1"),
        b"<< /Length "
        + str(len(compressed)).encode()
        + b" /Filter /FlateDecode >>\nstream\n"
        + compressed
        + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets[1:]:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_at}\n%%EOF\n"
    ).encode()
    return bytes(out)


class Handler(BaseHTTPRequestHandler):
    server_version = "MockAPISetu/1.0"

    def log_message(self, fmt, *args):
        print(f"  mock <- {fmt % args}", flush=True)

    def _send(self, status: int, body: bytes, content_type: str) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _error(self, status: int, message: str) -> None:
        payload = json.dumps({"error": status, "error_description": message}).encode()
        self._send(status, payload, "application/json")

    def do_POST(self) -> None:  # noqa: N802 - name mandated by BaseHTTPRequestHandler
        if self.path.rstrip("/") != PATH:
            self._error(404, f"unknown path {self.path}")
            return

        for header in EXPECTED_HEADERS:
            if not self.headers.get(header):
                self._error(401, f"missing {header} header")
                return

        length = int(self.headers.get("Content-Length") or 0)
        try:
            payload = json.loads(self.rfile.read(length) or b"{}")
        except json.JSONDecodeError:
            self._error(400, "request body is not valid JSON")
            return

        if not payload.get("txnId"):
            self._error(400, "txnId is required")
            return
        if payload.get("format") != "pdf":
            self._error(400, "format must be 'pdf'")
            return

        params = payload.get("certificateParameters") or {}
        uan = str(params.get("UAN", ""))
        dob = str(params.get("DOB", ""))

        if not UAN_RE.match(uan):
            self._error(400, "UAN must be exactly 12 digits")
            return
        if not DOB_RE.match(dob):
            self._error(400, "DOB must be in DD-MM-YYYY format")
            return

        marker = uan[-1]

        if marker == "2":
            self._error(404, "no UAN card found for the supplied UAN and date of birth")
            return

        if marker == "3":
            _attempts[uan] += 1
            if _attempts[uan] <= 2:
                self._error(503, "EPFO service temporarily unavailable")
                return

        if marker == "4":
            # The nasty one: HTTP 200, content-type says PDF, body is an error page.
            body = (
                b"<!doctype html><html><head><title>Service Notice</title></head>"
                b"<body><h1>Gateway maintenance</h1><p>Please retry later.</p>"
                b"</body></html>"
            )
            self._send(200, body, "application/pdf")
            return

        if marker == "5":
            full = build_pdf(uan, dob)
            self._send(200, full[: len(full) // 2], "application/pdf")
            return

        self._send(200, build_pdf(uan, dob, landscape=(marker == "1")), "application/pdf")


def main() -> None:
    server = ThreadingHTTPServer((HOST, PORT), Handler)
    print(f"Mock APISetu EPFO endpoint listening on http://{HOST}:{PORT}{PATH}")
    print("Point the tool at it with:")
    print(f"  APISETU_BASE_URL=http://{HOST}:{PORT}/epfindia/v3")
    print("Ctrl-C to stop.\n", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
